### ISSUE TITLE
Qualcomm parser run_diag: buf index out of range  

### ISSUE THREAD

**Issue by HandyMenny** [fgsect/scat#10]
Sometimes while parsing qmdl files I get "Index out of range" at this line:
https://github.com/fgsect/scat/blob/957d41dd00cd1b115129051767610556d1067a3b/parsers/qualcommparser.py#L184

For debugging purpose I added  `if len(buf) == 0:    self.logger.log(logging.DEBUG, util.xxd(buf))`  before and after this line: https://github.com/fgsect/scat/blob/957d41dd00cd1b115129051767610556d1067a3b/parsers/qualcommparser.py#L181

Here the output:
2019-04-27 14:51:31,361 scat.qualcommparser (run_diag) DEBUG: Hexdump:
-------- end --------
2019-04-27 14:51:31,361 scat.qualcommparser (run_diag) DEBUG: Hexdump:
-------- end --------
Traceback (most recent call last):
  File ".\scat.py", line 422, in <module>
    current_parser.read_dump()
  File "C:\Users\handy\Documents\GitHub\scat\parser2\qualcommparser.py", line 242, in read_dump
    self.run_diag()
  File "C:\Users\handy\Documents\GitHub\scat\parser2\qualcommparser.py", line 187, in run_diag
    if buf[-1] != 0x7e:
IndexError: index out of range

So len(buf) and len(oldbuf) is 0 in this case

**Comment by peremen** [comment]
So the error check is simple, and passes my test QMDL file test where the error is triggered. Can you please try the new master?

**Comment by HandyMenny** [comment]
I already tried, it works perfectly
