### ISSUE TITLE
IndexError: Invalid interface index for Motorola G5s plus.

### ISSUE THREAD

**Issue by r00tb3** [fgsect/scat#29]
Hi all, I'm trying to log baseband messages using diagnostics on a Motorola smartphone based on android 8.1.0 rooted and with supersu installed.

My USB info is:
```
Bus 003 Device 032: ID 22b8:2e76 Motorola PCS 
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            0 (Defined at Interface level)
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0        64
  idVendor           0x22b8 Motorola PCS
  idProduct          0x2e76 
  bcdDevice            3.18
  iManufacturer           1 motorola
  iProduct                2 Moto G (5S) Plus
  iSerial                 3 ZY322F833M
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength           62
    bNumInterfaces          2
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0x80
      (Bus Powered)
    MaxPower              500mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           3
      bInterfaceClass       255 Vendor Specific Class
      bInterfaceSubClass    255 Vendor Specific Subclass
      bInterfaceProtocol      0 
      iInterface              6 MTP
```
And after executing scat I get the following:

```
user$ python3 scat.py -D -t qc -u -a 003:032 -i 255
Trying USB device at address 003:032
  CONFIGURATION 1: 500 mA ==================================
   bLength              :    0x9 (9 bytes)
   bDescriptorType      :    0x2 Configuration
   wTotalLength         :   0x3e (62 bytes)
   bNumInterfaces       :    0x2
   bConfigurationValue  :    0x1
   iConfiguration       :    0x0 
   bmAttributes         :   0x80 Bus Powered
   bMaxPower            :   0xfa (500 mA)
    INTERFACE 0: Vendor Specific ===========================
     bLength            :    0x9 (9 bytes)
     bDescriptorType    :    0x4 Interface
     bInterfaceNumber   :    0x0
     bAlternateSetting  :    0x0
     bNumEndpoints      :    0x3
     bInterfaceClass    :   0xff Vendor Specific
     bInterfaceSubClass :   0xff
     bInterfaceProtocol :    0x0
     iInterface         :    0x6 MTP
      ENDPOINT 0x81: Bulk IN ===============================
       bLength          :    0x7 (7 bytes)
       bDescriptorType  :    0x5 Endpoint
       bEndpointAddress :   0x81 IN
       bmAttributes     :    0x2 Bulk
       wMaxPacketSize   :  0x200 (512 bytes)
       bInterval        :    0x0
      ENDPOINT 0x1: Bulk OUT ===============================
       bLength          :    0x7 (7 bytes)
       bDescriptorType  :    0x5 Endpoint
       bEndpointAddress :    0x1 OUT
       bmAttributes     :    0x2 Bulk
       wMaxPacketSize   :  0x200 (512 bytes)
       bInterval        :    0x0
      ENDPOINT 0x82: Interrupt IN ==========================
       bLength          :    0x7 (7 bytes)
       bDescriptorType  :    0x5 Endpoint
       bEndpointAddress :   0x82 IN
       bmAttributes     :    0x3 Interrupt
       wMaxPacketSize   :   0x1c (28 bytes)
       bInterval        :    0x6
    INTERFACE 1: Vendor Specific ===========================
     bLength            :    0x9 (9 bytes)
     bDescriptorType    :    0x4 Interface
     bInterfaceNumber   :    0x1
     bAlternateSetting  :    0x0
     bNumEndpoints      :    0x2
     bInterfaceClass    :   0xff Vendor Specific
     bInterfaceSubClass :   0x42
     bInterfaceProtocol :    0x1
     iInterface         :    0x7 ADB Interface
      ENDPOINT 0x2: Bulk OUT ===============================
       bLength          :    0x7 (7 bytes)
       bDescriptorType  :    0x5 Endpoint
       bEndpointAddress :    0x2 OUT
       bmAttributes     :    0x2 Bulk
       wMaxPacketSize   :  0x200 (512 bytes)
       bInterval        :    0x0
      ENDPOINT 0x83: Bulk IN ===============================
       bLength          :    0x7 (7 bytes)
       bDescriptorType  :    0x5 Endpoint
       bEndpointAddress :   0x83 IN
       bmAttributes     :    0x2 Bulk
       wMaxPacketSize   :  0x200 (512 bytes)
       bInterval        :    0x0
Traceback (most recent call last):
  File "scat.py", line 110, in <module>
    io_device.claim_interface(args.interface)
  File "/home/user/Desktop/tools/telco/BB/Qualcomm/scat/iodevices/usbio.py", line 66, in claim_interface
    self.intf = self.usb_cfg[(interface, 0)]
  File "/home/user/.local/lib/python3.6/site-packages/usb/core.py", line 641, in __getitem__
    return Interface(self.device, index[0], index[1], self.index)
  File "/home/user/.local/lib/python3.6/site-packages/usb/core.py", line 460, in __init__
    configuration
  File "/home/user/.local/lib/python3.6/site-packages/usb/backend/libusb1.py", line 767, in get_interface_descriptor
    raise IndexError('Invalid interface index ' + str(intf))
IndexError: Invalid interface index 255

```
Or after changing the interface to 0 or 1 I get the following:

```
user$ python3 scat.py -D -t qc -u -a 003:032 -i 0
Trying USB device at address 003:032
  CONFIGURATION 1: 500 mA ==================================
   bLength              :    0x9 (9 bytes)
   bDescriptorType      :    0x2 Configuration
   wTotalLength         :   0x3e (62 bytes)
   bNumInterfaces       :    0x2
   bConfigurationValue  :    0x1
   iConfiguration       :    0x0 
   bmAttributes         :   0x80 Bus Powered
   bMaxPower            :   0xfa (500 mA)
    INTERFACE 0: Vendor Specific ===========================
     bLength            :    0x9 (9 bytes)
     bDescriptorType    :    0x4 Interface
     bInterfaceNumber   :    0x0
     bAlternateSetting  :    0x0
     bNumEndpoints      :    0x3
     bInterfaceClass    :   0xff Vendor Specific
     bInterfaceSubClass :   0xff
     bInterfaceProtocol :    0x0
     iInterface         :    0x6 MTP
      ENDPOINT 0x81: Bulk IN ===============================
       bLength          :    0x7 (7 bytes)
       bDescriptorType  :    0x5 Endpoint
       bEndpointAddress :   0x81 IN
       bmAttributes     :    0x2 Bulk
       wMaxPacketSize   :  0x200 (512 bytes)
       bInterval        :    0x0
      ENDPOINT 0x1: Bulk OUT ===============================
       bLength          :    0x7 (7 bytes)
       bDescriptorType  :    0x5 Endpoint
       bEndpointAddress :    0x1 OUT
       bmAttributes     :    0x2 Bulk
       wMaxPacketSize   :  0x200 (512 bytes)
       bInterval        :    0x0
      ENDPOINT 0x82: Interrupt IN ==========================
       bLength          :    0x7 (7 bytes)
       bDescriptorType  :    0x5 Endpoint
       bEndpointAddress :   0x82 IN
       bmAttributes     :    0x3 Interrupt
       wMaxPacketSize   :   0x1c (28 bytes)
       bInterval        :    0x6
    INTERFACE 1: Vendor Specific ===========================
     bLength            :    0x9 (9 bytes)
     bDescriptorType    :    0x4 Interface
     bInterfaceNumber   :    0x1
     bAlternateSetting  :    0x0
     bNumEndpoints      :    0x2
     bInterfaceClass    :   0xff Vendor Specific
     bInterfaceSubClass :   0x42
     bInterfaceProtocol :    0x1
     iInterface         :    0x7 ADB Interface
      ENDPOINT 0x2: Bulk OUT ===============================
       bLength          :    0x7 (7 bytes)
       bDescriptorType  :    0x5 Endpoint
       bEndpointAddress :    0x2 OUT
       bmAttributes     :    0x2 Bulk
       wMaxPacketSize   :  0x200 (512 bytes)
       bInterval        :    0x0
      ENDPOINT 0x83: Bulk IN ===============================
       bLength          :    0x7 (7 bytes)
       bDescriptorType  :    0x5 Endpoint
       bEndpointAddress :   0x83 IN
       bmAttributes     :    0x2 Bulk
       wMaxPacketSize   :  0x200 (512 bytes)
       bInterval        :    0x0
2020-04-28 13:36:27,172 scat.qualcommparser (stop_diag) INFO: Stopping diag
Traceback (most recent call last):
  File "scat.py", line 149, in <module>
    current_parser.stop_diag()
  File "/home/user/Desktop/tools/telco/BB/Qualcomm/scat/parsers/qualcomm/qualcommparser.py", line 236, in stop_diag
    self.io_device.write_then_read_discard(util.generate_packet(struct.pack('<BB', diagcmd.DIAG_EVENT_REPORT_F, 0x00)), 0x1000, False)
  File "/home/user/Desktop/tools/telco/BB/Qualcomm/scat/iodevices/usbio.py", line 32, in write_then_read_discard
    self.write(write_buf, encode_hdlc)
  File "/home/user/Desktop/tools/telco/BB/Qualcomm/scat/iodevices/usbio.py", line 29, in write
    self.w_handle.write(write_buf)
  File "/home/user/.local/lib/python3.6/site-packages/usb/core.py", line 387, in write
    return self.device.write(self, data, timeout)
  File "/home/user/.local/lib/python3.6/site-packages/usb/core.py", line 940, in write
    intf, ep = self._ctx.setup_request(self, endpoint)
  File "/home/user/.local/lib/python3.6/site-packages/usb/core.py", line 102, in wrapper
    return f(self, *args, **kwargs)
  File "/home/user/.local/lib/python3.6/site-packages/usb/core.py", line 216, in setup_request
    self.managed_claim_interface(device, intf)
  File "/home/user/.local/lib/python3.6/site-packages/usb/core.py", line 102, in wrapper
    return f(self, *args, **kwargs)
  File "/home/user/.local/lib/python3.6/site-packages/usb/core.py", line 167, in managed_claim_interface
    self.backend.claim_interface(self.handle, i)
  File "/home/user/.local/lib/python3.6/site-packages/usb/backend/libusb1.py", line 811, in claim_interface
    _check(self.lib.libusb_claim_interface(dev_handle.handle, intf))
  File "/home/r00tb3/.local/lib/python3.6/site-packages/usb/backend/libusb1.py", line 595, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 16] Resource busy
```

What am I doing wrong?

Is the interface class wrong?

Pls, suggest a solution for the same.

**Comment by HandyMenny** [comment]
Looks like you've not enabled diag on you device. have you already tried with "setprop sys.usb.config diag,adb"?

**Comment by r00tb3** [comment]
> Looks like you've not enabled diag on you device. have you already tried with "setprop sys.usb.config diag,adb"?

I just executed  `setprop sys.usb.config diag,adb` after having shell access using `sudo adb shell` still facing the same error.

**Comment by peremen** [comment]
From what I've seen from the log, there is no Qualcomm DIAG interface detected. Usually DIAG interface has `bInterfaceClass == 0xff` and `bInterfaceSubClass == 0xff` but `iInterface` is something different from MTP and ADB.

**Comment by r00tb3** [comment]
> From what I've seen from the log, there is no Qualcomm DIAG interface detected. Usually DIAG interface has `bInterfaceClass == 0xff` and `bInterfaceSubClass == 0xff` but `iInterface` is something different from MTP and ADB.

I am able to log DIAG messages using [QCSuper](https://github.com/P1sec/QCSuper) without any issues.

But the same fails for SCAT.

**Comment by peremen** [comment]
> I am able to log DIAG messages using [QCSuper](https://github.com/P1sec/QCSuper) without any issues.

The main difference is that QCSuper uses an Android helper application on Android to pipe the diagnostic message to the application, while SCAT directly accesses the diagnostic port exposed via USB/serial. QCSuper-like approach using Android helper application is not planned in this moment.
