### ISSUE TITLE
UnboundLocalError: local variable 'rbid' referenced before assignment

### ISSUE THREAD

**Issue by olkitu** [fgsect/scat#58]
Error while trying export qmdl2 to pcap file

python3 ./scat.py -t qc -d qmdl2-file -F pcap-file

```
Traceback (most recent call last):
  File "./scat.py", line 171, in <module>
    current_parser.read_dump()
  File "/home/minh/git/scat/parsers/qualcomm/qualcommparser.py", line 271, in read_dump
    self.run_diag()
  File "/home/minh/git/scat/parsers/qualcomm/qualcommparser.py", line 225, in run_diag
    self.parse_diag(pkt)
  File "/home/minh/git/scat/parsers/qualcomm/qualcommparser.py", line 197, in parse_diag
    self.parse_diag_multisim(pkt)
  File "/home/minh/git/scat/parsers/qualcomm/qualcommparser.py", line 342, in parse_diag_multisim
    self.parse_diag(pkt_body, hdlc_encoded=False, check_crc=False, radio_id = (xdm_hdr[3]))
  File "/home/minh/git/scat/parsers/qualcomm/qualcommparser.py", line 185, in parse_diag
    self.parse_diag_log(pkt, radio_id)
  File "/home/minh/git/scat/parsers/qualcomm/qualcommparser.py", line 292, in parse_diag_log
    self.process[xdm_hdr[1]](pkt_ts, pkt_body, radio_id)
  File "/home/minh/git/scat/parsers/qualcomm/diagltelogparser.py", line 56, in <lambda>
    0xB0A5: lambda x, y, z: self.parse_lte_pdcp_dl_srb_int(x, y, z), # LTE PDCP DL SRB Integrity Data PDU
  File "/home/minh/git/scat/parsers/qualcomm/diagltelogparser.py", line 890, in parse_lte_pdcp_dl_srb_int
    if rbid == 0 or rbid == 1:
UnboundLocalError: local variable 'rbid' referenced before assignment
```

**Comment by peremen** [comment]
Please try with commit [d3e3d23](https://github.com/fgsect/scat/commit/d3e3d230fa5adb0acee30019078d467a8fd81b1e).
