### ISSUE TITLE
Device not found error while using base10 value 

### ISSUE THREAD

**Issue by sramar** [fgsect/scat#80]
**Software branch : v1.1.0**
 I'm using base10 value "scat -t qc -u -a 1256:26717 -i 2" but getting error "Device not found".  Can you please help on this issue 

lsusb commands output : Bus 004 Device 006: ID 04e8:685d Samsung Electronics Co., Ltd GT-I9100 Phone [Galaxy S II] (Download mode)

**scat -t qc -u -a 1256:26717 -i 2**
Trying USB device at address 1256:26717
Traceback (most recent call last):
  File "/usr/local/bin/scat", line 8, in <module>
    sys.exit(scat_main())
  File "/usr/local/lib/python3.8/dist-packages/scat/main.py", line 123, in scat_main
    io_device.probe_device_by_bus_dev(usb_bus, usb_device)
  File "/usr/local/lib/python3.8/dist-packages/scat/iodevices/usbio.py", line 49, in probe_device_by_bus_dev
    raise ValueError('Device not found')
ValueError: Device not found

Best Regards,
Ramar

**Comment by peremen** [comment]
`-a` is the USB bus/device address, not the VID/PID. Please use `-v 04e8 -p 685d` or `-a 004:006` instead.
